package service

import "errors"

var (
	ErrUsernameTooLong       = errors.New("Le nom d'utilisateur est trop long.")
	ErrUsernameRequired      = errors.New("Le nom d'utilisateur est requis.")
	ErrPasswordTooLong       = errors.New("Le mot de passe est trop long.")
	ErrPasswordRequired      = errors.New("Le mot de passe est requis.")
	ErrNonExistantAccount    = errors.New("Aucun compte n'est associé à ce nom d'utilisateur.")
	ErrWrongPassword         = errors.New("Mot de passe incorrect.")
	ErrInvalidEmail          = errors.New("Adresse e-mail invalide.")
	ErrUserAlreadyExist      = errors.New("Cet utilisateur existe déjà.")
	ErrInvalidCSV            = errors.New("Fichier CSV invalide.")
	ErrInvalidCSVHeader      = errors.New("En-tête du fichier CSV invalide.")
	ErrInvalidInput          = errors.New("Données saisies invalides.")
	ErrUserNotFound          = errors.New("Utilisateur introuvable.")
	ErrInternalError         = errors.New("Erreur interne du serveur.")
	ErrInvalidActivationCode = errors.New("Le code d'activation est invalide.")
	ErrActivationCodeExpired = errors.New("Le code d'activation a expiré.")
	ErrInvalidPassword       = errors.New("Le mot de passe ne respecte pas les critères demandés.")
	ErrContestNotFound       = errors.New("Concours introuvable.")
	ErrNameTooLong           = errors.New("Le nom est trop long.")
	ErrSlugTooLong           = errors.New("Le slug est trop long.")
	ErrEmptyName             = errors.New("Le nom ne peut pas être vide.")
	ErrEmptySlug             = errors.New("Le slug ne peut pas être vide.")
	ErrContestAlreadyExists  = errors.New("Ce concours existe déjà.")
	ErrDirectoryExists       = errors.New("Ce répertoire existe déjà.")
	ErrInvalidTimeRange      = errors.New("La plage horaire est invalide.")
	ErrDifficultyNotFound    = errors.New("Niveau de difficulté introuvable.")
	ErrProblemNotFound       = errors.New("Problème introuvable.")
	ErrPartTooBig            = errors.New("Cette partie est trop volumineuse.")
	ErrCreatingData          = errors.New("Erreur interne lors de la création des données du problème.")
	ErrContestNotStarted     = errors.New("Le concours n'a pas encore commencé.")
	ErrContestFinished       = errors.New("Le concours est terminé.")
	ErrOutputNotFound        = errors.New("Output introuvable pour cet utilisateur.")
	ErrUnableToSolve         = errors.New("Impossible de résoudre le problème.")
	ErrUnableToCreateProblem = errors.New("Impossible de créer le problème.")
	ErrPartNotFound          = errors.New("Une partie est introuvable.")
	ErrAlreadySolved         = errors.New("Cette partie a déjà été résolue.")
	ErrInputNotFound         = errors.New("Input introuvable pour cet utilisateur")
)
