// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSiteConfigIfMissing = `-- name: CreateSiteConfigIfMissing :execrows
INSERT OR IGNORE INTO site_config
    (id, site_title, main_text, secondary_text, current_contest,
     help_content, rules_content, legal_content, credits_content)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSiteConfigIfMissingParams struct {
	SiteTitle      string
	MainText       string
	SecondaryText  string
	CurrentContest string
	HelpContent    string
	RulesContent   string
	LegalContent   string
	CreditsContent string
}

func (q *Queries) CreateSiteConfigIfMissing(ctx context.Context, arg CreateSiteConfigIfMissingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSiteConfigIfMissing,
		arg.SiteTitle,
		arg.MainText,
		arg.SecondaryText,
		arg.CurrentContest,
		arg.HelpContent,
		arg.RulesContent,
		arg.LegalContent,
		arg.CreditsContent,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSiteConfig = `-- name: GetSiteConfig :one
SELECT id, site_title, main_text, secondary_text, current_contest, help_content, rules_content, legal_content, credits_content FROM site_config WHERE id = 1
`

func (q *Queries) GetSiteConfig(ctx context.Context) (SiteConfig, error) {
	row := q.db.QueryRowContext(ctx, getSiteConfig)
	var i SiteConfig
	err := row.Scan(
		&i.ID,
		&i.SiteTitle,
		&i.MainText,
		&i.SecondaryText,
		&i.CurrentContest,
		&i.HelpContent,
		&i.RulesContent,
		&i.LegalContent,
		&i.CreditsContent,
	)
	return i, err
}

const updateSiteConfig = `-- name: UpdateSiteConfig :exec
UPDATE site_config SET
    site_title      = COALESCE(?1, site_title),
    main_text       = COALESCE(?2, main_text),
    secondary_text  = COALESCE(?3, secondary_text),
    current_contest = COALESCE(?4, current_contest),
    help_content    = COALESCE(?5, help_content),
    rules_content   = COALESCE(?6, rules_content),
    legal_content   = COALESCE(?7, legal_content),
    credits_content = COALESCE(?8, credits_content)
WHERE id = 1
`

type UpdateSiteConfigParams struct {
	SiteTitle      sql.NullString
	MainText       sql.NullString
	SecondaryText  sql.NullString
	CurrentContest sql.NullString
	HelpContent    sql.NullString
	RulesContent   sql.NullString
	LegalContent   sql.NullString
	CreditsContent sql.NullString
}

func (q *Queries) UpdateSiteConfig(ctx context.Context, arg UpdateSiteConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteConfig,
		arg.SiteTitle,
		arg.MainText,
		arg.SecondaryText,
		arg.CurrentContest,
		arg.HelpContent,
		arg.RulesContent,
		arg.LegalContent,
		arg.CreditsContent,
	)
	return err
}
