// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contest.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createContest = `-- name: CreateContest :one
INSERT INTO contests (slug, name, description, start_at, end_at, unlisted, auto_generate, mode, infinite)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, name, description, start_at, end_at, unlisted, auto_generate, mode, infinite
`

type CreateContestParams struct {
	Slug         string
	Name         string
	Description  string
	StartAt      int64
	EndAt        int64
	Unlisted     bool
	AutoGenerate bool
	Mode         string
	Infinite     bool
}

func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRowContext(ctx, createContest,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.Unlisted,
		arg.AutoGenerate,
		arg.Mode,
		arg.Infinite,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.Unlisted,
		&i.AutoGenerate,
		&i.Mode,
		&i.Infinite,
	)
	return i, err
}

const deleteContest = `-- name: DeleteContest :execrows
DELETE FROM contests WHERE id = ?
`

func (q *Queries) DeleteContest(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContest = `-- name: GetContest :one
SELECT id, slug, name, description, start_at, end_at, unlisted, auto_generate, mode, infinite FROM contests WHERE id = ?
`

func (q *Queries) GetContest(ctx context.Context, id int64) (Contest, error) {
	row := q.db.QueryRowContext(ctx, getContest, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.Unlisted,
		&i.AutoGenerate,
		&i.Mode,
		&i.Infinite,
	)
	return i, err
}

const getContestBySlug = `-- name: GetContestBySlug :one
SELECT id, slug, name, description, start_at, end_at, unlisted, auto_generate, mode, infinite FROM contests WHERE slug = ?
`

func (q *Queries) GetContestBySlug(ctx context.Context, slug string) (Contest, error) {
	row := q.db.QueryRowContext(ctx, getContestBySlug, slug)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.Unlisted,
		&i.AutoGenerate,
		&i.Mode,
		&i.Infinite,
	)
	return i, err
}

const listArchivedContests = `-- name: ListArchivedContests :many
SELECT id, slug, name, description, start_at, end_at, unlisted, auto_generate, mode, infinite FROM contests WHERE unlisted = FALSE ORDER BY start_at DESC
`

func (q *Queries) ListArchivedContests(ctx context.Context) ([]Contest, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.Unlisted,
			&i.AutoGenerate,
			&i.Mode,
			&i.Infinite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoGenerateContests = `-- name: ListAutoGenerateContests :many
SELECT id, slug, name, description, start_at, end_at, unlisted, auto_generate, mode, infinite FROM contests WHERE auto_generate = TRUE AND mode = 'normal' ORDER BY id
`

func (q *Queries) ListAutoGenerateContests(ctx context.Context) ([]Contest, error) {
	rows, err := q.db.QueryContext(ctx, listAutoGenerateContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.Unlisted,
			&i.AutoGenerate,
			&i.Mode,
			&i.Infinite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContests = `-- name: ListContests :many
SELECT id, slug, name, description, start_at, end_at, unlisted, auto_generate, mode, infinite FROM contests ORDER BY start_at DESC
`

func (q *Queries) ListContests(ctx context.Context) ([]Contest, error) {
	rows, err := q.db.QueryContext(ctx, listContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.Unlisted,
			&i.AutoGenerate,
			&i.Mode,
			&i.Infinite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContest = `-- name: UpdateContest :execrows
UPDATE contests SET
    slug        = COALESCE(?1, slug),
    name        = COALESCE(?2, name),
    description = COALESCE(?3, description),
    unlisted    = COALESCE(?4, unlisted),
    auto_generate = COALESCE(?5, auto_generate),
    mode        = COALESCE(?6, mode),
    infinite    = COALESCE(?7, infinite),
    start_at    = COALESCE(?8, start_at),
    end_at      = COALESCE(?9, end_at)
WHERE id = ?10
`

type UpdateContestParams struct {
	Slug         sql.NullString
	Name         sql.NullString
	Description  sql.NullString
	Unlisted     sql.NullBool
	AutoGenerate sql.NullBool
	Mode         sql.NullString
	Infinite     sql.NullBool
	StartAt      sql.NullInt64
	EndAt        sql.NullInt64
	ID           int64
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContest,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Unlisted,
		arg.AutoGenerate,
		arg.Mode,
		arg.Infinite,
		arg.StartAt,
		arg.EndAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
