// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contest.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createContest = `-- name: CreateContest :one
INSERT INTO contests (slug, name, description, start_at, end_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, slug, name, description, start_at, end_at
`

type CreateContestParams struct {
	Slug        string
	Name        string
	Description string
	StartAt     int64
	EndAt       int64
}

func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRowContext(ctx, createContest,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}

const getContest = `-- name: GetContest :one
SELECT id, slug, name, description, start_at, end_at FROM contests WHERE id = ?
`

func (q *Queries) GetContest(ctx context.Context, id int64) (Contest, error) {
	row := q.db.QueryRowContext(ctx, getContest, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}

const getContestBySlug = `-- name: GetContestBySlug :one
SELECT id, slug, name, description, start_at, end_at FROM contests WHERE slug = ?
`

func (q *Queries) GetContestBySlug(ctx context.Context, slug string) (Contest, error) {
	row := q.db.QueryRowContext(ctx, getContestBySlug, slug)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}

const listContests = `-- name: ListContests :many
SELECT id, slug, name, description, start_at, end_at FROM contests ORDER BY start_at DESC
`

func (q *Queries) ListContests(ctx context.Context) ([]Contest, error) {
	rows, err := q.db.QueryContext(ctx, listContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContest = `-- name: UpdateContest :execrows
UPDATE contests SET
    slug        = COALESCE(?1, slug),
    name        = COALESCE(?2, name),
    description = COALESCE(?3, description),
    start_at    = COALESCE(?4, start_at),
    end_at      = COALESCE(?5, end_at)
WHERE id = ?6
`

type UpdateContestParams struct {
	Slug        sql.NullString
	Name        sql.NullString
	Description sql.NullString
	StartAt     sql.NullInt64
	EndAt       sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContest,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
