// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation.sql

package sqlc

import (
	"context"
	"database/sql"
)

const claimGenerationTask = `-- name: ClaimGenerationTask :one
UPDATE generation_tasks
SET status = 'running', started_at = ?, finished_at = NULL, error = ''
WHERE id = (
    SELECT id FROM generation_tasks WHERE status = 'queued' ORDER BY id LIMIT 1
)
RETURNING id, run_id, problem_id, user_id, shared, status, error, created_at, started_at, finished_at
`

func (q *Queries) ClaimGenerationTask(ctx context.Context, startedAt sql.NullInt64) (GenerationTask, error) {
	row := q.db.QueryRowContext(ctx, claimGenerationTask, startedAt)
	var i GenerationTask
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ProblemID,
		&i.UserID,
		&i.Shared,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createGenerationRun = `-- name: CreateGenerationRun :one
INSERT INTO generation_runs (contest_id, source, mode, status, created_at)
VALUES (?, ?, ?, 'queued', ?)
RETURNING id, contest_id, source, mode, status, created_at, started_at, finished_at
`

type CreateGenerationRunParams struct {
	ContestID int64
	Source    string
	Mode      string
	CreatedAt int64
}

func (q *Queries) CreateGenerationRun(ctx context.Context, arg CreateGenerationRunParams) (GenerationRun, error) {
	row := q.db.QueryRowContext(ctx, createGenerationRun,
		arg.ContestID,
		arg.Source,
		arg.Mode,
		arg.CreatedAt,
	)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Source,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createGenerationTask = `-- name: CreateGenerationTask :one
INSERT INTO generation_tasks (run_id, problem_id, user_id, shared, status, error, created_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, run_id, problem_id, user_id, shared, status, error, created_at, started_at, finished_at
`

type CreateGenerationTaskParams struct {
	RunID      int64
	ProblemID  int64
	UserID     sql.NullInt64
	Shared     bool
	Status     string
	Error      string
	CreatedAt  int64
	FinishedAt sql.NullInt64
}

func (q *Queries) CreateGenerationTask(ctx context.Context, arg CreateGenerationTaskParams) (GenerationTask, error) {
	row := q.db.QueryRowContext(ctx, createGenerationTask,
		arg.RunID,
		arg.ProblemID,
		arg.UserID,
		arg.Shared,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
		arg.FinishedAt,
	)
	var i GenerationTask
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ProblemID,
		&i.UserID,
		&i.Shared,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishGenerationRun = `-- name: FinishGenerationRun :exec
UPDATE generation_runs
SET status = ?, finished_at = ?
WHERE id = ?
`

type FinishGenerationRunParams struct {
	Status     string
	FinishedAt sql.NullInt64
	ID         int64
}

func (q *Queries) FinishGenerationRun(ctx context.Context, arg FinishGenerationRunParams) error {
	_, err := q.db.ExecContext(ctx, finishGenerationRun, arg.Status, arg.FinishedAt, arg.ID)
	return err
}

const finishIdleGenerationRuns = `-- name: FinishIdleGenerationRuns :exec
UPDATE generation_runs
SET status = CASE
        WHEN EXISTS (
            SELECT 1 FROM generation_tasks
            WHERE run_id = generation_runs.id AND status = 'failed'
        ) THEN 'completed_with_errors'
        ELSE 'completed'
    END,
    finished_at = ?
WHERE status IN ('queued', 'running')
  AND NOT EXISTS (
      SELECT 1 FROM generation_tasks
      WHERE run_id = generation_runs.id AND status IN ('queued', 'running')
  )
`

func (q *Queries) FinishIdleGenerationRuns(ctx context.Context, finishedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, finishIdleGenerationRuns, finishedAt)
	return err
}

const generationTaskCounts = `-- name: GenerationTaskCounts :one
SELECT
    CAST(COUNT(*) AS INTEGER) AS total,
    CAST(COUNT(*) FILTER (WHERE status = 'queued') AS INTEGER) AS queued,
    CAST(COUNT(*) FILTER (WHERE status = 'running') AS INTEGER) AS running,
    CAST(COUNT(*) FILTER (WHERE status = 'succeeded') AS INTEGER) AS succeeded,
    CAST(COUNT(*) FILTER (WHERE status = 'failed') AS INTEGER) AS failed,
    CAST(COUNT(*) FILTER (WHERE status = 'skipped') AS INTEGER) AS skipped
FROM generation_tasks
WHERE run_id = ?
`

type GenerationTaskCountsRow struct {
	Total     int64
	Queued    int64
	Running   int64
	Succeeded int64
	Failed    int64
	Skipped   int64
}

func (q *Queries) GenerationTaskCounts(ctx context.Context, runID int64) (GenerationTaskCountsRow, error) {
	row := q.db.QueryRowContext(ctx, generationTaskCounts, runID)
	var i GenerationTaskCountsRow
	err := row.Scan(
		&i.Total,
		&i.Queued,
		&i.Running,
		&i.Succeeded,
		&i.Failed,
		&i.Skipped,
	)
	return i, err
}

const getGenerationRun = `-- name: GetGenerationRun :one
;

SELECT generation_runs.id, generation_runs.contest_id, generation_runs.source, generation_runs.mode, generation_runs.status, generation_runs.created_at, generation_runs.started_at, generation_runs.finished_at, contests.name AS contest_name
FROM generation_runs
JOIN contests ON contests.id = generation_runs.contest_id
WHERE generation_runs.id = ?
`

type GetGenerationRunRow struct {
	ID          int64
	ContestID   int64
	Source      string
	Mode        string
	Status      string
	CreatedAt   int64
	StartedAt   sql.NullInt64
	FinishedAt  sql.NullInt64
	ContestName string
}

func (q *Queries) GetGenerationRun(ctx context.Context, id int64) (GetGenerationRunRow, error) {
	row := q.db.QueryRowContext(ctx, getGenerationRun, id)
	var i GetGenerationRunRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Source,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ContestName,
	)
	return i, err
}

const getGenerationTaskDetail = `-- name: GetGenerationTaskDetail :one
SELECT generation_tasks.id, generation_tasks.run_id, generation_tasks.problem_id, generation_tasks.user_id, generation_tasks.shared, generation_tasks.status, generation_tasks.error, generation_tasks.created_at, generation_tasks.started_at, generation_tasks.finished_at, generation_runs.id, generation_runs.contest_id, generation_runs.source, generation_runs.mode, generation_runs.status, generation_runs.created_at, generation_runs.started_at, generation_runs.finished_at,
       COALESCE(users.username, 'free-play') AS username,
       problems.id, problems.contest_id, problems.difficulty_id, problems.slug, problems.name, problems.author, problems.parts, problems.points_multiplier, problems.points_adder, problems.hidden, contests.id, contests.slug, contests.name, contests.description, contests.start_at, contests.end_at, contests.unlisted, contests.auto_generate, contests.mode, contests.infinite
FROM generation_tasks
JOIN generation_runs ON generation_runs.id = generation_tasks.run_id
LEFT JOIN users ON users.id = generation_tasks.user_id
JOIN problems ON problems.id = generation_tasks.problem_id
JOIN contests ON contests.id = problems.contest_id
WHERE generation_tasks.id = ?
`

type GetGenerationTaskDetailRow struct {
	GenerationTask GenerationTask
	GenerationRun  GenerationRun
	Username       string
	Problem        Problem
	Contest        Contest
}

func (q *Queries) GetGenerationTaskDetail(ctx context.Context, id int64) (GetGenerationTaskDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getGenerationTaskDetail, id)
	var i GetGenerationTaskDetailRow
	err := row.Scan(
		&i.GenerationTask.ID,
		&i.GenerationTask.RunID,
		&i.GenerationTask.ProblemID,
		&i.GenerationTask.UserID,
		&i.GenerationTask.Shared,
		&i.GenerationTask.Status,
		&i.GenerationTask.Error,
		&i.GenerationTask.CreatedAt,
		&i.GenerationTask.StartedAt,
		&i.GenerationTask.FinishedAt,
		&i.GenerationRun.ID,
		&i.GenerationRun.ContestID,
		&i.GenerationRun.Source,
		&i.GenerationRun.Mode,
		&i.GenerationRun.Status,
		&i.GenerationRun.CreatedAt,
		&i.GenerationRun.StartedAt,
		&i.GenerationRun.FinishedAt,
		&i.Username,
		&i.Problem.ID,
		&i.Problem.ContestID,
		&i.Problem.DifficultyID,
		&i.Problem.Slug,
		&i.Problem.Name,
		&i.Problem.Author,
		&i.Problem.Parts,
		&i.Problem.PointsMultiplier,
		&i.Problem.PointsAdder,
		&i.Problem.Hidden,
		&i.Contest.ID,
		&i.Contest.Slug,
		&i.Contest.Name,
		&i.Contest.Description,
		&i.Contest.StartAt,
		&i.Contest.EndAt,
		&i.Contest.Unlisted,
		&i.Contest.AutoGenerate,
		&i.Contest.Mode,
		&i.Contest.Infinite,
	)
	return i, err
}

const hasActiveGenerationTask = `-- name: HasActiveGenerationTask :one
SELECT CAST(EXISTS (
    SELECT 1 FROM generation_tasks
    WHERE problem_id = ? AND user_id = ? AND shared = FALSE AND status IN ('queued', 'running')
) AS BOOLEAN)
`

type HasActiveGenerationTaskParams struct {
	ProblemID int64
	UserID    sql.NullInt64
}

func (q *Queries) HasActiveGenerationTask(ctx context.Context, arg HasActiveGenerationTaskParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveGenerationTask, arg.ProblemID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasActiveSharedGenerationTask = `-- name: HasActiveSharedGenerationTask :one
SELECT CAST(EXISTS (
    SELECT 1 FROM generation_tasks
    WHERE problem_id = ? AND shared = TRUE AND status IN ('queued', 'running')
) AS BOOLEAN)
`

func (q *Queries) HasActiveSharedGenerationTask(ctx context.Context, problemID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveSharedGenerationTask, problemID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listGenerationRuns = `-- name: ListGenerationRuns :many
SELECT generation_runs.id, generation_runs.contest_id, generation_runs.source, generation_runs.mode, generation_runs.status, generation_runs.created_at, generation_runs.started_at, generation_runs.finished_at,
       contests.name AS contest_name,
       CAST(COUNT(generation_tasks.id) AS INTEGER) AS total,
       CAST(COUNT(generation_tasks.id) FILTER (WHERE generation_tasks.status = 'queued') AS INTEGER) AS queued,
       CAST(COUNT(generation_tasks.id) FILTER (WHERE generation_tasks.status = 'running') AS INTEGER) AS running,
       CAST(COUNT(generation_tasks.id) FILTER (WHERE generation_tasks.status = 'succeeded') AS INTEGER) AS succeeded,
       CAST(COUNT(generation_tasks.id) FILTER (WHERE generation_tasks.status = 'failed') AS INTEGER) AS failed,
       CAST(COUNT(generation_tasks.id) FILTER (WHERE generation_tasks.status = 'skipped') AS INTEGER) AS skipped
FROM generation_runs
JOIN contests ON contests.id = generation_runs.contest_id
LEFT JOIN generation_tasks ON generation_tasks.run_id = generation_runs.id
WHERE generation_runs.status IN ('queued', 'running')
   OR generation_runs.id IN (SELECT id FROM generation_runs ORDER BY id DESC LIMIT ?)
GROUP BY generation_runs.id
ORDER BY generation_runs.id DESC
`

type ListGenerationRunsRow struct {
	ID          int64
	ContestID   int64
	Source      string
	Mode        string
	Status      string
	CreatedAt   int64
	StartedAt   sql.NullInt64
	FinishedAt  sql.NullInt64
	ContestName string
	Total       int64
	Queued      int64
	Running     int64
	Succeeded   int64
	Failed      int64
	Skipped     int64
}

func (q *Queries) ListGenerationRuns(ctx context.Context, limit int64) ([]ListGenerationRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGenerationRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenerationRunsRow{}
	for rows.Next() {
		var i ListGenerationRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.Source,
			&i.Mode,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ContestName,
			&i.Total,
			&i.Queued,
			&i.Running,
			&i.Succeeded,
			&i.Failed,
			&i.Skipped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationTasksByRun = `-- name: ListGenerationTasksByRun :many
SELECT generation_tasks.id, generation_tasks.run_id, generation_tasks.problem_id, generation_tasks.user_id, generation_tasks.shared, generation_tasks.status, generation_tasks.error, generation_tasks.created_at, generation_tasks.started_at, generation_tasks.finished_at, COALESCE(users.username, 'Jeu libre') AS username,
       problems.name AS problem_name
FROM generation_tasks
LEFT JOIN users ON users.id = generation_tasks.user_id
JOIN problems ON problems.id = generation_tasks.problem_id
WHERE generation_tasks.run_id = ?
ORDER BY generation_tasks.id
`

type ListGenerationTasksByRunRow struct {
	ID          int64
	RunID       int64
	ProblemID   int64
	UserID      sql.NullInt64
	Shared      bool
	Status      string
	Error       string
	CreatedAt   int64
	StartedAt   sql.NullInt64
	FinishedAt  sql.NullInt64
	Username    string
	ProblemName string
}

func (q *Queries) ListGenerationTasksByRun(ctx context.Context, runID int64) ([]ListGenerationTasksByRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listGenerationTasksByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenerationTasksByRunRow{}
	for rows.Next() {
		var i ListGenerationTasksByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ProblemID,
			&i.UserID,
			&i.Shared,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Username,
			&i.ProblemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGenerationRunStarted = `-- name: MarkGenerationRunStarted :exec
UPDATE generation_runs
SET status = 'running', started_at = COALESCE(started_at, ?)
WHERE id = ? AND status = 'queued'
`

type MarkGenerationRunStartedParams struct {
	StartedAt sql.NullInt64
	ID        int64
}

func (q *Queries) MarkGenerationRunStarted(ctx context.Context, arg MarkGenerationRunStartedParams) error {
	_, err := q.db.ExecContext(ctx, markGenerationRunStarted, arg.StartedAt, arg.ID)
	return err
}

const recoverGenerationRuns = `-- name: RecoverGenerationRuns :exec
UPDATE generation_runs
SET status = 'queued', started_at = NULL, finished_at = NULL
WHERE status = 'running'
`

func (q *Queries) RecoverGenerationRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverGenerationRuns)
	return err
}

const recoverGenerationTasks = `-- name: RecoverGenerationTasks :exec
UPDATE generation_tasks
SET status = 'queued', started_at = NULL, error = ''
WHERE status = 'running'
`

func (q *Queries) RecoverGenerationTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverGenerationTasks)
	return err
}

const updateGenerationTask = `-- name: UpdateGenerationTask :exec
UPDATE generation_tasks
SET status = ?, error = ?, finished_at = ?
WHERE id = ?
`

type UpdateGenerationTaskParams struct {
	Status     string
	Error      string
	FinishedAt sql.NullInt64
	ID         int64
}

func (q *Queries) UpdateGenerationTask(ctx context.Context, arg UpdateGenerationTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateGenerationTask,
		arg.Status,
		arg.Error,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
