// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type ActivationCode struct {
	Code      string
	UserID    int64
	ExpiresAt int64
	UsedAt    sql.NullInt64
}

type Contest struct {
	ID          int64
	Slug        string
	Name        string
	Description string
	StartAt     int64
	EndAt       int64
}

type Difficulty struct {
	ID     int64
	Name   string
	Points int64
}

type Problem struct {
	ID               int64
	ContestID        int64
	DifficultyID     int64
	Slug             string
	Name             string
	Author           string
	Parts            int64
	PointsMultiplier float64
	PointsAdder      int64
}

type ProblemInput struct {
	ProblemID int64
	UserID    int64
	Input     string
}

type ProblemOutput struct {
	ProblemID int64
	UserID    int64
	Part      int64
	Output    string
}

type SiteConfig struct {
	ID             int64
	SiteTitle      string
	MainText       string
	SecondaryText  string
	CurrentContest string
	HelpContent    string
	RulesContent   string
	LegalContent   string
	CreditsContent string
}

type Solve struct {
	UserID    int64
	ProblemID int64
	Parts     int64
	SolvedAt  int64
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Activated    bool
	Admin        bool
	CreatedAt    int64
}
