// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problem.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDifficulty = `-- name: CreateDifficulty :one
INSERT INTO difficulties (name, points) VALUES (?, ?) RETURNING id, name, points
`

type CreateDifficultyParams struct {
	Name   string
	Points int64
}

func (q *Queries) CreateDifficulty(ctx context.Context, arg CreateDifficultyParams) (Difficulty, error) {
	row := q.db.QueryRowContext(ctx, createDifficulty, arg.Name, arg.Points)
	var i Difficulty
	err := row.Scan(&i.ID, &i.Name, &i.Points)
	return i, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (contest_id, difficulty_id, slug, name, author, parts, points_multiplier, points_adder)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, contest_id, difficulty_id, slug, name, author, parts, points_multiplier, points_adder
`

type CreateProblemParams struct {
	ContestID        int64
	DifficultyID     int64
	Slug             string
	Name             string
	Author           string
	Parts            int64
	PointsMultiplier float64
	PointsAdder      int64
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.ContestID,
		arg.DifficultyID,
		arg.Slug,
		arg.Name,
		arg.Author,
		arg.Parts,
		arg.PointsMultiplier,
		arg.PointsAdder,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.DifficultyID,
		&i.Slug,
		&i.Name,
		&i.Author,
		&i.Parts,
		&i.PointsMultiplier,
		&i.PointsAdder,
	)
	return i, err
}

const getDifficultyByName = `-- name: GetDifficultyByName :one
SELECT id, name, points FROM difficulties WHERE name = ?
`

func (q *Queries) GetDifficultyByName(ctx context.Context, name string) (Difficulty, error) {
	row := q.db.QueryRowContext(ctx, getDifficultyByName, name)
	var i Difficulty
	err := row.Scan(&i.ID, &i.Name, &i.Points)
	return i, err
}

const getProblemBySlug = `-- name: GetProblemBySlug :one
SELECT problems.id, problems.contest_id, problems.difficulty_id, problems.slug, problems.name, problems.author, problems.parts, problems.points_multiplier, problems.points_adder, contests.id, contests.slug, contests.name, contests.description, contests.start_at, contests.end_at, contests.unlisted, difficulties.id, difficulties.name, difficulties.points
FROM problems
JOIN contests     ON contests.id = problems.contest_id
JOIN difficulties ON difficulties.id = problems.difficulty_id
WHERE problems.slug = ?
`

type GetProblemBySlugRow struct {
	Problem    Problem
	Contest    Contest
	Difficulty Difficulty
}

func (q *Queries) GetProblemBySlug(ctx context.Context, slug string) (GetProblemBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getProblemBySlug, slug)
	var i GetProblemBySlugRow
	err := row.Scan(
		&i.Problem.ID,
		&i.Problem.ContestID,
		&i.Problem.DifficultyID,
		&i.Problem.Slug,
		&i.Problem.Name,
		&i.Problem.Author,
		&i.Problem.Parts,
		&i.Problem.PointsMultiplier,
		&i.Problem.PointsAdder,
		&i.Contest.ID,
		&i.Contest.Slug,
		&i.Contest.Name,
		&i.Contest.Description,
		&i.Contest.StartAt,
		&i.Contest.EndAt,
		&i.Contest.Unlisted,
		&i.Difficulty.ID,
		&i.Difficulty.Name,
		&i.Difficulty.Points,
	)
	return i, err
}

const getProblemInput = `-- name: GetProblemInput :one
SELECT input FROM problem_inputs WHERE problem_id = ? AND user_id = ?
`

type GetProblemInputParams struct {
	ProblemID int64
	UserID    int64
}

func (q *Queries) GetProblemInput(ctx context.Context, arg GetProblemInputParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProblemInput, arg.ProblemID, arg.UserID)
	var input string
	err := row.Scan(&input)
	return input, err
}

const getProblemOutput = `-- name: GetProblemOutput :one
SELECT output FROM problem_outputs WHERE problem_id = ? AND user_id = ? AND part = ?
`

type GetProblemOutputParams struct {
	ProblemID int64
	UserID    int64
	Part      int64
}

func (q *Queries) GetProblemOutput(ctx context.Context, arg GetProblemOutputParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProblemOutput, arg.ProblemID, arg.UserID, arg.Part)
	var output string
	err := row.Scan(&output)
	return output, err
}

const getSolvedParts = `-- name: GetSolvedParts :one
SELECT CAST(COALESCE((SELECT parts FROM solves WHERE user_id = ? AND problem_id = ?), 0) AS INTEGER)
`

type GetSolvedPartsParams struct {
	UserID    int64
	ProblemID int64
}

func (q *Queries) GetSolvedParts(ctx context.Context, arg GetSolvedPartsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSolvedParts, arg.UserID, arg.ProblemID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listProblemsByContest = `-- name: ListProblemsByContest :many
SELECT problems.id, problems.contest_id, problems.difficulty_id, problems.slug, problems.name, problems.author, problems.parts, problems.points_multiplier, problems.points_adder, difficulties.id, difficulties.name, difficulties.points
FROM problems
JOIN difficulties ON difficulties.id = problems.difficulty_id
WHERE problems.contest_id = ?
ORDER BY difficulties.points, problems.name
`

type ListProblemsByContestRow struct {
	Problem    Problem
	Difficulty Difficulty
}

func (q *Queries) ListProblemsByContest(ctx context.Context, contestID int64) ([]ListProblemsByContestRow, error) {
	rows, err := q.db.QueryContext(ctx, listProblemsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemsByContestRow{}
	for rows.Next() {
		var i ListProblemsByContestRow
		if err := rows.Scan(
			&i.Problem.ID,
			&i.Problem.ContestID,
			&i.Problem.DifficultyID,
			&i.Problem.Slug,
			&i.Problem.Name,
			&i.Problem.Author,
			&i.Problem.Parts,
			&i.Problem.PointsMultiplier,
			&i.Problem.PointsAdder,
			&i.Difficulty.ID,
			&i.Difficulty.Name,
			&i.Difficulty.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblem = `-- name: UpdateProblem :execrows
UPDATE problems SET
    slug              = COALESCE(?1, slug),
    name              = COALESCE(?2, name),
    author            = COALESCE(?3, author),
    parts             = COALESCE(?4, parts),
    points_multiplier = COALESCE(?5, points_multiplier),
    points_adder      = COALESCE(?6, points_adder)
WHERE id = ?7
`

type UpdateProblemParams struct {
	Slug             sql.NullString
	Name             sql.NullString
	Author           sql.NullString
	Parts            sql.NullInt64
	PointsMultiplier sql.NullFloat64
	PointsAdder      sql.NullInt64
	ID               int64
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProblem,
		arg.Slug,
		arg.Name,
		arg.Author,
		arg.Parts,
		arg.PointsMultiplier,
		arg.PointsAdder,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProblemInput = `-- name: UpsertProblemInput :exec
INSERT INTO problem_inputs (problem_id, user_id, input) VALUES (?, ?, ?)
ON CONFLICT (problem_id, user_id) DO UPDATE SET input = excluded.input
`

type UpsertProblemInputParams struct {
	ProblemID int64
	UserID    int64
	Input     string
}

func (q *Queries) UpsertProblemInput(ctx context.Context, arg UpsertProblemInputParams) error {
	_, err := q.db.ExecContext(ctx, upsertProblemInput, arg.ProblemID, arg.UserID, arg.Input)
	return err
}

const upsertProblemOutput = `-- name: UpsertProblemOutput :exec
INSERT INTO problem_outputs (problem_id, user_id, part, output) VALUES (?, ?, ?, ?)
ON CONFLICT (problem_id, user_id, part) DO UPDATE SET output = excluded.output
`

type UpsertProblemOutputParams struct {
	ProblemID int64
	UserID    int64
	Part      int64
	Output    string
}

func (q *Queries) UpsertProblemOutput(ctx context.Context, arg UpsertProblemOutputParams) error {
	_, err := q.db.ExecContext(ctx, upsertProblemOutput,
		arg.ProblemID,
		arg.UserID,
		arg.Part,
		arg.Output,
	)
	return err
}

const upsertSolve = `-- name: UpsertSolve :exec
INSERT INTO solves (user_id, problem_id, parts, solved_at) VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, problem_id) DO UPDATE
    SET parts = excluded.parts, solved_at = excluded.solved_at
    WHERE excluded.parts > solves.parts
`

type UpsertSolveParams struct {
	UserID    int64
	ProblemID int64
	Parts     int64
	SolvedAt  int64
}

func (q *Queries) UpsertSolve(ctx context.Context, arg UpsertSolveParams) error {
	_, err := q.db.ExecContext(ctx, upsertSolve,
		arg.UserID,
		arg.ProblemID,
		arg.Parts,
		arg.SolvedAt,
	)
	return err
}
