// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users SET password_hash = ?, activated = TRUE WHERE id = ?
`

type ActivateUserParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) error {
	_, err := q.db.ExecContext(ctx, activateUser, arg.PasswordHash, arg.ID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivationCode = `-- name: CreateActivationCode :exec
INSERT INTO activation_codes (code, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateActivationCodeParams struct {
	Code      string
	UserID    int64
	ExpiresAt int64
}

func (q *Queries) CreateActivationCode(ctx context.Context, arg CreateActivationCodeParams) error {
	_, err := q.db.ExecContext(ctx, createActivationCode, arg.Code, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, activated, admin, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, username, email, password_hash, activated, admin, created_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	Activated    bool
	Admin        bool
	CreatedAt    int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Activated,
		arg.Admin,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const createUserIfMissing = `-- name: CreateUserIfMissing :execrows
INSERT OR IGNORE INTO users (username, email, password_hash, activated, admin, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserIfMissingParams struct {
	Username     string
	Email        string
	PasswordHash string
	Activated    bool
	Admin        bool
	CreatedAt    int64
}

func (q *Queries) CreateUserIfMissing(ctx context.Context, arg CreateUserIfMissingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUserIfMissing,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Activated,
		arg.Admin,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActivationCode = `-- name: GetActivationCode :one
SELECT activation_codes.code, activation_codes.user_id, activation_codes.expires_at, activation_codes.used_at, users.id, users.username, users.email, users.password_hash, users.activated, users.admin, users.created_at
FROM activation_codes
JOIN users ON users.id = activation_codes.user_id
WHERE activation_codes.code = ?
`

type GetActivationCodeRow struct {
	ActivationCode ActivationCode
	User           User
}

func (q *Queries) GetActivationCode(ctx context.Context, code string) (GetActivationCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getActivationCode, code)
	var i GetActivationCodeRow
	err := row.Scan(
		&i.ActivationCode.Code,
		&i.ActivationCode.UserID,
		&i.ActivationCode.ExpiresAt,
		&i.ActivationCode.UsedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.Activated,
		&i.User.Admin,
		&i.User.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password_hash, activated, admin, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, activated, admin, created_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const leaderboard = `-- name: Leaderboard :many
SELECT u.id, u.username,
       CAST(SUM((d.points * p.points_multiplier + p.points_adder) * s.parts) AS REAL) AS score
FROM users u
JOIN solves s       ON s.user_id = u.id
JOIN problems p     ON p.id = s.problem_id
JOIN difficulties d ON d.id = p.difficulty_id
WHERE u.admin = FALSE AND u.activated = TRUE AND p.contest_id = ?
GROUP BY u.id, u.username
HAVING score > 0
ORDER BY score DESC, u.username ASC
`

type LeaderboardRow struct {
	ID       int64
	Username string
	Score    float64
}

func (q *Queries) Leaderboard(ctx context.Context, contestID int64) ([]LeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, leaderboard, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardRow{}
	for rows.Next() {
		var i LeaderboardRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingActivations = `-- name: ListPendingActivations :many
SELECT activation_codes.code, activation_codes.user_id, activation_codes.expires_at, activation_codes.used_at, users.id, users.username, users.email, users.password_hash, users.activated, users.admin, users.created_at
FROM activation_codes
JOIN users ON users.id = activation_codes.user_id
WHERE activation_codes.used_at IS NULL AND users.activated = FALSE
ORDER BY users.username
`

type ListPendingActivationsRow struct {
	ActivationCode ActivationCode
	User           User
}

func (q *Queries) ListPendingActivations(ctx context.Context) ([]ListPendingActivationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingActivations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingActivationsRow{}
	for rows.Next() {
		var i ListPendingActivationsRow
		if err := rows.Scan(
			&i.ActivationCode.Code,
			&i.ActivationCode.UserID,
			&i.ActivationCode.ExpiresAt,
			&i.ActivationCode.UsedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.Activated,
			&i.User.Admin,
			&i.User.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET admin = ? WHERE id = ?
`

type SetUserAdminParams struct {
	Admin bool
	ID    int64
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.ExecContext(ctx, setUserAdmin, arg.Admin, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const useActivationCode = `-- name: UseActivationCode :execrows
UPDATE activation_codes SET used_at = ? WHERE code = ? AND used_at IS NULL
`

type UseActivationCodeParams struct {
	UsedAt sql.NullInt64
	Code   string
}

func (q *Queries) UseActivationCode(ctx context.Context, arg UseActivationCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useActivationCode, arg.UsedAt, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
